services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: medicitas_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar_net

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: medicitas_sonar_scanner
    profiles:
      - scan
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=sqp_9fa349c02a4e0f350f9c3711b506f8c9fef17683
    volumes:
      - ./:/usr/src
    networks:
      - sonar_net
    depends_on:
      - sonarqube

networks:
  sonar_net:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
