sonar.projectKey=Medicitas-Backend
sonar.projectName=Medicitas Backend
sonar.projectVersion=1.0

# Directorio principal a analizar
sonar.sources=src

# Exclusiones
sonar.exclusions=**/node_modules/**,**/test/**,**/*.test.js

# Codificación
sonar.sourceEncoding=UTF-8
